//go:build integration

package playback

// Deterministic integration evidence for the playback compatibility service
// (run inside a disposable task-labelled Docker container with FFmpeg
// installed; never against host tools). Gated by the `integration` build tag
// AND TORWATCH_PLAYBACK_INTEGRATION=1.
//
// Fixtures are GENERATED by FFmpeg inside the run: tiny MP4 (H.264/AAC),
// MKV (H.264/AAC), an MPEG4-Part-2 MP4 (transcode case), and a malformed
// file. No peers, no magnets, no network torrents.

import (
	"context"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func integrationEnabled(t *testing.T) (Tools, string) {
	t.Helper()
	if os.Getenv("TORWATCH_PLAYBACK_INTEGRATION") != "1" {
		t.Skip("integration evidence requires TORWATCH_PLAYBACK_INTEGRATION=1")
	}
	tools := Tools{FFprobePath: "ffprobe", FFmpegPath: "ffmpeg"}
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	if ok, why := tools.Available(ctx); !ok {
		t.Skipf("ffmpeg toolchain unavailable: %s", why)
	}
	dir := t.TempDir()
	return tools, dir
}

func generateFixture(t *testing.T, ffmpeg string, args []string, out string) string {
	t.Helper()
	cmd := exec.Command(ffmpeg, append(append([]string{"-nostdin", "-loglevel", "error", "-y"}, args...), out)...)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("fixture generation failed (%s): %v: %s", out, err, string(output))
	}
	if _, err := os.Stat(out); err != nil {
		t.Fatalf("fixture missing: %v", err)
	}
	return out
}

func TestIntegrationProbePlanRemuxTranscodeSubtitles(t *testing.T) {
	tools, workDir := integrationEnabled(t)
	ctx := context.Background()

	mp4 := generateFixture(t, tools.FFmpegPath, []string{
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x240:rate=10",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=2",
		"-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest",
	}, filepath.Join(workDir, "sample.mp4"))
	mkv := generateFixture(t, tools.FFmpegPath, []string{
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x240:rate=10",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=2",
		"-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
	}, filepath.Join(workDir, "sample.mkv"))
	mpeg4 := generateFixture(t, tools.FFmpegPath, []string{
		"-f", "lavfi", "-i", "testsrc=duration=2:size=320x240:rate=10",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=2",
		"-c:v", "mpeg4", "-c:a", "aac", "-shortest",
	}, filepath.Join(workDir, "legacy.mp4"))
	malformed := filepath.Join(workDir, "garbage.mp4")
	if err := os.WriteFile(malformed, []byte(strings.Repeat("\x00TORWATCH", 512)), 0o644); err != nil {
		t.Fatalf("malformed fixture: %v", err)
	}

	prober := &FFprobeProber{Tools: tools, Timeout: 30 * time.Second}

	// Direct: MP4 H.264/AAC inspects and plans direct.
	info, err := prober.Probe(ctx, mp4)
	if err != nil {
		t.Fatalf("mp4 probe: %v", err)
	}
	if d := Plan(PlanInput{Info: info, Profile: DefaultProfiles()["ios-avplayer"], FFmpegReady: true}); d.Mode != ModeDirect {
		t.Fatalf("mp4 plan = %s/%s", d.Mode, d.ReasonCode)
	}

	// Malformed input → bounded failure, no panic, no path in the error.
	if _, err := prober.Probe(ctx, malformed); err == nil {
		t.Fatal("malformed input must fail inspection")
	} else if strings.Contains(err.Error(), workDir) {
		t.Fatalf("probe error leaks local paths: %v", err)
	}

	// Loopback media source: ffprobe must succeed through the token URL.
	ms, err := NewMediaSource()
	if err != nil {
		t.Fatalf("media source: %v", err)
	}
	defer ms.Close()
	token, srcURL, err := ms.Issue(func() (io.ReadSeekCloser, error) {
		return os.Open(mkv)
	}, "sample.mkv", fileSize(t, mkv), 10*time.Minute)
	_ = token
	if err != nil {
		t.Fatalf("issue: %v", err)
	}
	mkvInfo, err := prober.Probe(ctx, srcURL)
	if err != nil {
		t.Fatalf("mkv probe via loopback source: %v", err)
	}
	decision := Plan(PlanInput{Info: mkvInfo, Profile: DefaultProfiles()["ios-avplayer"], FFmpegReady: true})
	if decision.Mode != ModeRemux || !decision.CopyVideo || !decision.CopyAudio {
		t.Fatalf("mkv plan = %s (copy=%v/%v)", decision.Mode, decision.CopyVideo, decision.CopyAudio)
	}

	// Remux: stream-copy MKV to HLS/fMP4 through the loopback source.
	sessionDir := filepath.Join(workDir, "sess-remux")
	if err := os.MkdirAll(sessionDir, 0o755); err != nil {
		t.Fatalf("session dir: %v", err)
	}
	runner := &Runner{FFmpegPath: tools.FFmpegPath}
	runCtx, cancel := context.WithCancel(ctx)
	defer cancel()
	if err := runner.Start(runCtx, srcURL, decision, sessionDir); err != nil {
		t.Fatalf("remux start: %v", err)
	}
	waitForFile(t, filepath.Join(sessionDir, "playlist.m3u8"), 30*time.Second)
	waitForPattern(t, sessionDir, "*.m4s", 30*time.Second)
	cancel()
	runner.Stop()

	playlist, _ := os.ReadFile(filepath.Join(sessionDir, "playlist.m3u8"))
	if !strings.Contains(string(playlist), "#EXTM3U") {
		t.Fatalf("variant playlist malformed: %s", string(playlist)[:80])
	}

	// Transcode: MPEG4-Part-2 source plans transcode and produces segments.
	transcodeInfo, err := prober.Probe(ctx, mpeg4)
	if err != nil {
		t.Fatalf("mpeg4 probe: %v", err)
	}
	td := Plan(PlanInput{Info: transcodeInfo, Profile: DefaultProfiles()["ios-avplayer"], FFmpegReady: true, MaxTranscodeHeight: 1080})
	if td.Mode != ModeTranscode {
		t.Fatalf("mpeg4 plan = %s/%s", td.Mode, td.ReasonCode)
	}
	tDir := filepath.Join(workDir, "sess-transcode")
	if err := os.MkdirAll(tDir, 0o755); err != nil {
		t.Fatalf("transcode dir: %v", err)
	}
	runner2 := &Runner{FFmpegPath: tools.FFmpegPath}
	if err := runner2.Start(ctx, "file://"+mpeg4, td, tDir); err != nil {
		t.Fatalf("transcode start: %v", err)
	}
	waitForFile(t, filepath.Join(tDir, "playlist.m3u8"), 45*time.Second)
	runner2.Stop()

	// Master playlist: no magnets, correct structure, subtitle group only
	// when offers exist.
	mkvSession := &session{hls: true, decision: Decision{Mode: ModeRemux, CopyVideo: true, CopyAudio: true}, view: SessionView{Info: mkvInfo, Subtitles: []SubtitleOffer{{
		ID: "t0", Language: "en", Label: "English", URL: "/v2/playback/sessions/x/subtitles/t0.vtt",
	}}}}
	master := WriteMasterPlaylist(mkvSession)
	if strings.Contains(master, "magnet") || strings.Contains(master, srcURL) {
		t.Fatalf("master playlist leaks source material")
	}
	if !strings.Contains(master, "#EXT-X-STREAM-INF") || !strings.Contains(master, "SUBTITLES=\"subs\"") {
		t.Fatalf("master playlist structure wrong:\n%s", master)
	}
}

func fileSize(t *testing.T, path string) int64 {
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	return info.Size()
}

func waitForFile(t *testing.T, path string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if info, err := os.Stat(path); err == nil && info.Size() > 0 {
			return
		}
		time.Sleep(250 * time.Millisecond)
	}
	t.Fatalf("file never appeared: %s", path)
}

func waitForPattern(t *testing.T, dir, pattern string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		matches, _ := filepath.Glob(filepath.Join(dir, pattern))
		if len(matches) > 0 {
			return
		}
		time.Sleep(250 * time.Millisecond)
	}
	t.Fatalf("no %s files appeared in %s", pattern, dir)
}
