-- 009_downloads.sql — offline downloads (docs/offline-downloads D01).
-- Purely additive: new tables only; no existing table or column is altered.
-- Old binaries ignore these tables; downgrade is safe (retained rows simply
-- expire by the documented lifecycle). See docs/offline-downloads/contracts.md §7.

-- Persistent server-instance identity (contracts §1): exactly one row,
-- created once, never regenerated by restarts or re-runs.
CREATE TABLE IF NOT EXISTS server_instance (
  singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO server_instance (singleton, id)
VALUES (TRUE, gen_random_uuid())
ON CONFLICT (singleton) DO NOTHING;

-- Durable preparation jobs (contracts §3).
CREATE TABLE IF NOT EXISTS download_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  idempotency_key TEXT NOT NULL,
  client_id TEXT NOT NULL,
  series_id TEXT NOT NULL,
  season INT NOT NULL DEFAULT 0 CHECK (season >= 0),
  episode INT NOT NULL DEFAULT 0 CHECK (episode >= 0),
  pick_id BIGINT NOT NULL,
  state TEXT NOT NULL CHECK (state IN ('preparing','ready','failed','cancelled','expired')),
  reason_code TEXT NOT NULL DEFAULT '',
  manifest JSONB NULL,
  requested_subtitles TEXT NOT NULL DEFAULT '',
  claimed_by TEXT NOT NULL DEFAULT '',
  claimed_at TIMESTAMPTZ NULL,
  ready_at TIMESTAMPTZ NULL,
  expires_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (client_id, idempotency_key),
  -- (state, reason_code) pairs are the closed contract enumeration.
  CHECK (
    (state = 'preparing' AND reason_code = '') OR
    (state = 'ready' AND reason_code = '') OR
    (state = 'failed' AND reason_code IN ('source_unavailable','insufficient_server_storage','preparation_failed')) OR
    (state = 'cancelled' AND reason_code IN ('client_cancelled','replaced')) OR
    (state = 'expired' AND reason_code = 'retention_expired')
  ),
  CHECK ((state = 'ready') = (ready_at IS NOT NULL))
);
DROP TRIGGER IF EXISTS trg_download_jobs_upd ON download_jobs;
CREATE TRIGGER trg_download_jobs_upd BEFORE UPDATE ON download_jobs
FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE INDEX IF NOT EXISTS idx_download_jobs_state ON download_jobs(state);
CREATE INDEX IF NOT EXISTS idx_download_jobs_expiry ON download_jobs(expires_at) WHERE state = 'ready';

-- Immutable per-job assets (contracts §4). url_path is the public,
-- origin-relative URL owned by the job; asset_path is the server-relative
-- disk location under the downloads root. No credentials, magnets, or
-- provider data are stored.
CREATE TABLE IF NOT EXISTS download_assets (
  job_id UUID NOT NULL REFERENCES download_jobs(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('video','subtitle')),
  lang TEXT NOT NULL DEFAULT '',
  url_path TEXT NOT NULL,
  asset_path TEXT NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
  sha256 TEXT NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (job_id, url_path),
  UNIQUE (url_path)
);

-- Idempotency ledger for offline progress import (contracts §6).
CREATE TABLE IF NOT EXISTS offline_progress_updates (
  client_id TEXT NOT NULL,
  update_id TEXT NOT NULL,
  series_id TEXT NOT NULL,
  season INT NOT NULL,
  episode INT NOT NULL,
  outcome TEXT NOT NULL CHECK (outcome IN ('committed','duplicate')),
  committed_revision BIGINT NOT NULL,
  position_s INT NOT NULL,
  duration_s INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (client_id, update_id)
);
