from pathlib import Path
import json
import sys
root=Path(sys.argv[1]).resolve(); out=Path(sys.argv[2]).resolve(); out.mkdir(parents=True, exist_ok=True)
cases={
'internal/recommendations':r'''package recommendations
import("context";"errors";"testing")
type auditFlakyTaste struct{ calls int }
func(f *auditFlakyTaste) HouseholdSignals(context.Context)([]TasteSignal,error){f.calls++;if f.calls<=3{return nil,errors.New("taste store unavailable")};return nil,nil}
func TestAuditTasteFailureFallback(t *testing.T){taste:=&auditFlakyTaste{};s:=New(Deps{Library:&fakeLibrary{revision:1},Candidates:&fakeCandidates{},SeedGenres:&fakeSeedGenres{},Taste:taste});_,err:=s.Recommend(context.Background());if err!=nil{t.Fatal(err)};if taste.calls!=1{t.Errorf("Recommend(taste failure) called taste %d times, want one followed by legacy fallback",taste.calls)}}
''',
'internal/search':r'''package search
import("context";"net/http";"net/http/httptest";"testing")
func TestAuditEmptyProwlarrResults(t *testing.T){srv:=httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){w.Write([]byte(`[]`))}));defer srv.Close();s,err:=NewService(srv.URL,"test-key",srv.Client());if err!=nil{t.Fatal(err)};found,err:=s.query(context.Background(),prowlarrQuery{query:"No Such Movie",kind:KindMovie});if err!=nil||len(found)!=0{t.Errorf("query(empty successful response) got len=%d err=%v, want zero results with no error",len(found),err)}}
''',
'internal/catalog':r'''package catalog
import("context";"encoding/json";"fmt";"sync";"testing";"time")
func TestAuditCachedCatalogOwnership(t *testing.T){a:=Title{ID:"tmdb:movie:1",Title:"Film",Type:TypeMovie,Year:2020,ProviderIDs:map[string]string{"tmdb":"movie:1"},Artwork:map[string]string{"poster":"a"}};b:=Title{ID:"imdb:tt1",Title:"Film",Type:TypeMovie,Year:2020,ProviderIDs:map[string]string{"imdb":"tt1"},Artwork:map[string]string{"background":"b"}};MergeTitles([][]Title{{a},{b}});if a.ProviderIDs["imdb"]!=""||a.Artwork["background"]!=""{t.Errorf("MergeTitles mutated cached provider input: ids=%v artwork=%v, want input unchanged",a.ProviderIDs,a.Artwork)}}
func TestAuditConcurrentCachedCatalog(t *testing.T){s:=NewService([]Provider{&fakeProvider{name:"a"},&fakeProvider{name:"b"}},Options{});q:=SearchQuery{Query:"Film",Limit:50};var a,b []Title;for i:=0;i<300;i++{a=append(a,Title{ID:fmt.Sprintf("tmdb:movie:%d",i+1),Title:fmt.Sprintf("Film %d",i),Type:TypeMovie,ProviderIDs:map[string]string{"tmdb":"a"},Artwork:map[string]string{"poster":"a"}});b=append(b,Title{ID:fmt.Sprintf("imdb:tt%d",i+1),Title:fmt.Sprintf("Film %d",i),Type:TypeMovie,ProviderIDs:map[string]string{"imdb":"b"},Artwork:map[string]string{"background":"b"}})};s.cache.Set("a",searchCacheKey(q),a,time.Hour);s.cache.Set("b",searchCacheKey(q),b,time.Hour);var wg sync.WaitGroup;start:=make(chan struct{});for i:=0;i<12;i++{wg.Add(1);go func(){defer wg.Done();<-start;r:=s.Search(context.Background(),q);_,_=json.Marshal(r)}()};close(start);wg.Wait()}
''',
'internal/downloads':r'''package downloads
import("context";"database/sql";"os";"strings";"testing";"time";"torrent-streamer/migrations")
func auditStore(t *testing.T)(*Store,Job){t.Helper();db,err:=sql.Open("pgx",os.Getenv("TORWATCH_TEST_PG_DSN"));if err!=nil{t.Fatal(err)};t.Cleanup(func(){db.Close()});ctx:=context.Background();if err:=migrations.Apply(ctx,db);err!=nil{t.Fatal(err)};s:=NewStore(db);j,_,err:=s.Create(ctx,CreateRequest{ClientID:"audit-client",IdempotencyKey:t.Name()+time.Now().Format("150405.000000000"),SeriesID:"tmdb:movie:1",PickID:1});if err!=nil{t.Fatal(err)};return s,j}
func TestAuditRenewManifest(t *testing.T){s,j:=auditStore(t);ctx:=context.Background();now:=time.Now().UTC();path:="/v1/downloads/jobs/"+j.ID+"/assets/video";m:=Manifest{ManifestVersion:1,JobID:j.ID,Revision:1,ExpiresAt:now.Add(time.Hour).Format(time.RFC3339),Video:Asset{Kind:AssetKindVideo,Path:path,SizeBytes:1,SHA256:strings.Repeat("a",64)}};if err:=s.MarkReady(ctx,j.ID,m,[]AssetRow{{Kind:AssetKindVideo,URLPath:path,DiskPath:"ready/"+j.ID+"/video.mp4",SizeBytes:1,SHA256:strings.Repeat("a",64)}},now.Add(-47*time.Hour));err!=nil{t.Fatal(err)};renewed,err:=s.Renew(ctx,j.ClientID,j.ID,now);if err!=nil{t.Fatal(err)};m,err=s.Manifest(ctx,j.ClientID,j.ID);if err!=nil{t.Fatal(err)};if m.ExpiresAt!=renewed.ExpiresAt.UTC().Format(time.RFC3339){t.Errorf("Renew expiry=%s but Manifest expiry=%s, want same expiry",renewed.ExpiresAt,m.ExpiresAt)}}
func TestAuditLiveClaimIsReset(t *testing.T){s,j:=auditStore(t);ctx:=context.Background();if _,err:=s.ClaimPreparing(ctx,j.ID,"live-worker");err!=nil{t.Fatal(err)};if _,err:=s.DB.ExecContext(ctx,`UPDATE download_jobs SET claimed_at=now()-interval '16 minutes' WHERE id=$1`,j.ID);err!=nil{t.Fatal(err)};n,err:=s.ResetStaleClaims(ctx,15*time.Minute);if err!=nil{t.Fatal(err)};if n!=0{t.Errorf("ResetStaleClaims reset %d still-running claims, want zero",n)};_,err=s.ClaimPreparing(ctx,j.ID,"second-worker");if err==nil{t.Errorf("ClaimPreparing admitted second worker for active job %s",j.ID)}}
''',
'internal/torrentx':r'''package torrentx
import("context";"net";"os";"os/exec";"strconv";"strings";"testing";"time";"github.com/anacrolix/torrent";"github.com/anacrolix/torrent/bencode";"github.com/anacrolix/torrent/metainfo";"torrent-streamer/internal/config")
func TestAuditCategoryPortCollision(t *testing.T){if os.Getenv("TORWATCH_AUDIT_PORT_CHILD")=="1"{config.Load();GetClientFor("movie");GetClientFor("tv");CloseAllClients();return};l,err:=net.Listen("tcp","127.0.0.1:0");if err!=nil{t.Fatal(err)};port:=l.Addr().(*net.TCPAddr).Port;l.Close();ctx,cancel:=context.WithTimeout(context.Background(),10*time.Second);defer cancel();cmd:=exec.CommandContext(ctx,os.Args[0],"-test.run=^TestAuditCategoryPortCollision$");cmd.Env=append(os.Environ(),"TORWATCH_AUDIT_PORT_CHILD=1","TORRENT_DATA_ROOT="+t.TempDir(),"TORRENT_LISTEN_PORT="+strconv.Itoa(port));output,err:=cmd.CombinedOutput();if err!=nil&&strings.Contains(string(output),"address already in use"){t.Errorf("GetClientFor(movie), GetClientFor(tv) terminated backend: %s",output)}else if err!=nil{t.Fatal(err,string(output))}}
func TestAuditStalledReaderClose(t *testing.T){cfg:=torrent.NewDefaultClientConfig();cfg.DataDir=t.TempDir();cfg.ListenPort=0;cfg.DisableUTP=true;cfg.NoDHT=true;cfg.DisableTrackers=true;cfg.DisablePEX=true;cl,err:=torrent.NewClient(cfg);if err!=nil{t.Fatal(err)};defer cl.Close();info:=metainfo.Info{Name:"audit.mp4",Length:16384,PieceLength:16384,Pieces:make([]byte,20)};raw,err:=bencode.Marshal(info);if err!=nil{t.Fatal(err)};tt,err:=cl.AddTorrent(&metainfo.MetaInfo{InfoBytes:raw});if err!=nil{t.Fatal(err)};rd:=tt.Files()[0].NewReader();done:=make(chan struct{});go func(){defer close(done);Prebuffer(rd,1,50*time.Millisecond)}();select{case <-done:t.Fatal("unexpected read before data available");case <-time.After(200*time.Millisecond):};rd.Close();select{case <-done:case <-time.After(200*time.Millisecond):t.Error("Prebuffer(50ms) still blocked after 400ms and Reader.Close; want bounded read")};tt.Drop();select{case <-done:case <-time.After(time.Second):t.Fatal("cleanup did not unblock read")}}
'''
}

cases['internal/httpapi'] = 'package httpapi\nimport("net/http";"net/http/httptest";"strings";"testing")\nfunc TestAuditDownloadPreflight(t *testing.T){h:=newDownloadsTestHandlers(&fakeDownloadService{});h.AllowedOrigins=[]string{"http://localhost:5173"};m:=http.NewServeMux();h.Register(m);r:=httptest.NewRequest("OPTIONS","/v1/downloads/jobs",nil);r.Header.Set("Origin","http://localhost:5173");r.Header.Set("Access-Control-Request-Method","POST");r.Header.Set("Access-Control-Request-Headers","content-type");w:=httptest.NewRecorder();m.ServeHTTP(w,r);if !strings.Contains(w.Header().Get("Access-Control-Allow-Methods"),"POST"){t.Errorf("download POST preflight methods=%q, want POST allowed",w.Header().Get("Access-Control-Allow-Methods"))}}\nfunc TestAuditTastePreflight(t *testing.T){m:=http.NewServeMux();RegisterTasteRoutes(m,nil);r:=httptest.NewRequest("OPTIONS","/v1/taste/visited",nil);r.Header.Set("Origin","http://localhost:5173");r.Header.Set("Access-Control-Request-Method","POST");w:=httptest.NewRecorder();m.ServeHTTP(w,r);if w.Code>=400{t.Errorf("taste preflight returned %d, want success",w.Code)}}\n'
cases['internal/playback'] = 'package playback\nimport("testing")\nfunc TestAuditIncompatibleHDRPlan(t *testing.T){d:=Plan(PlanInput{Info:&MediaInfo{Container:"mkv",Video:VideoInfo{Codec:"av1"},Audio:AudioInfo{Codec:"aac"},HDR:"hdr10",Height:2160,Width:3840},Profile:DefaultProfiles()["android-media3"],FFmpegReady:true,TranscodeAllowed:true});if d.Mode!=ModeUnsupported||d.ReasonCode!=ReasonHDRUnsupported{t.Errorf("AV1 HDR on SDR profile got %s/%s, want unsupported HDR because runner has no tone mapping",d.Mode,d.ReasonCode)}}\n'
cases['internal/logx'] = 'package logx\nimport("fmt";"io";"testing";"time")\nfunc TestAuditZeroWindowLogRetention(t *testing.T){w:=New(io.Discard,0,"","");for i:=0;i<10000;i++{fmt.Fprintf(w,"request %d at %s",i,time.Now())};if len(w.lastSeen)!=0{t.Errorf("zero-window diagnostic writer retained %d unique records, want no dedup history",len(w.lastSeen))}}\n'

replace={}
for pkg,code in cases.items():
    target=out/(pkg.replace('/','_')+'_audit_test.go');target.write_text(code)
    replace[str(root/pkg/'z_audit_review_test.go')]=str(target)
(out/'overlay.json').write_text(json.dumps({'Replace':replace}))
